yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,6 +1,9 @@
 name: CI Pipeline
 
 on:
+  push:
+    branches:
+      - main
   pull_request:
     branches:
       - main
@@ -23,13 +26,7 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install flake8 pylint mypy black isort
-      
-      - name: Run Isort
-        run: isort .
-
-      - name: Run Black
-        run: black .
+          pip install flake8 pylint mypy
 
       - name: Run Flake8
         run: flake8 .
@@ -74,12 +71,17 @@ jobs:
             echo "changed=false" >> $GITHUB_ENV
           fi
 
+      - name: Pull latest changes from the remote branch
+        if: env.changed == 'true'
+        run: |
+          git fetch origin
+          git rebase origin/${{ github.head_ref }}
+
       - name: Push formatting changes back to PR branch
         if: env.changed == 'true'
         run: |
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
           git add .
-          git commit -m "Auto-format code"
-          git push origin HEAD:${{ github.head_ref }}
-
+          git commit -m "Auto-format code" || echo "No changes to commit"
+          git push origin HEAD:${{ github.head_ref }} || echo "Failed to push changes"
