yaml changes

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -48,25 +48,38 @@ jobs:
           git add .
           git commit -m "Auto-format code"
           git push origin $BRANCH_NAME
-          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV  # Setting the environment variable
+          echo $BRANCH_NAME > branch_name.txt
+          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
+          echo "::set-output name=branch::$BRANCH_NAME"  # Setting the output for branch
+
+      - name: Upload branch name artifact
+        if: env.changed == 'true'
+        uses: actions/upload-artifact@v3
+        with:
+          name: branch_name
+          path: branch_name.txt
 
   lint-and-checks:
     needs: auto-format
     runs-on: ubuntu-latest
-    if: needs.auto-format.outputs.branch != '' && env.changed == 'true'
+    if: needs.auto-format.outputs.branch != ''
     steps:
+      - name: Download branch name artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: branch_name
+
       - name: Checkout formatted branch
         uses: actions/checkout@v3
         with:
-          ref: ${{ env.BRANCH_NAME }}
+          ref: ${{ env.branch_name }}
 
       - name: Verify checked out branch
         run: |
           CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
           echo "Checked out branch: $CURRENT_BRANCH"
-          if [ "$CURRENT_BRANCH" != "${{ env.BRANCH_NAME }}" ]; then
-            echo "Error: Checked out branch ($CURRENT_BRANCH) does not match expected branch (${{
-            env.BRANCH_NAME }})"
+          if [ "$CURRENT_BRANCH" != "${{ env.branch_name }}" ]; then
+            echo "Error: Checked out branch ($CURRENT_BRANCH) does not match expected branch (${{ env.branch_name }})"
             exit 1
           fi
 
@@ -108,11 +121,22 @@ jobs:
       - name: Checkout the repository
         uses: actions/checkout@v3
 
+      - name: Download branch name artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: branch_name
+
+      - name: Read branch name
+        id: read-branch
+        run: |
+          BRANCH_NAME=$(cat branch_name.txt)
+          echo "Branch to delete: $BRANCH_NAME"
+          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
+
       - name: Delete temporary branch
         run: |
-          BRANCH_NAME="${{ env.BRANCH_NAME }}"
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
-          git push origin --delete $BRANCH_NAME || true
+          git push origin --delete ${{ env.branch_name }} || true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
